definitions:
  model.Audience:
    properties:
      ageFrom:
        type: integer
      ageTo:
        type: integer
      birthCountry:
        type: string
      gender:
        type: integer
      hoursSpentFrom:
        type: integer
      hoursSpentTo:
        type: integer
      id:
        type: string
      purchasesFrom:
        type: integer
      purchasesTo:
        type: integer
    type: object
  model.Chart:
    properties:
      dataPoints:
        items:
          $ref: '#/definitions/model.DataPoint'
        type: array
      id:
        type: string
      title:
        type: string
      xaxisTitle:
        type: string
      yaxisTitle:
        type: string
    type: object
  model.DataPoint:
    properties:
      x:
        type: number
      "y":
        type: number
    type: object
  model.Insight:
    properties:
      description:
        type: string
      id:
        type: string
    type: object
  model.UserFavourite:
    properties:
      audience:
        $ref: '#/definitions/model.Audience'
      chart:
        $ref: '#/definitions/model.Chart'
      description:
        type: string
      insight:
        $ref: '#/definitions/model.Insight'
    type: object
  model.UserFavouriteShort:
    properties:
      description:
        type: string
      id:
        type: string
      resourceType:
        type: string
    type: object
info:
  contact: {}
  title: Favourites API
paths:
  /favourites:
    post:
      description: creates a favourite for a specified user
      parameters:
      - description: UserFavouriteShort to create
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserFavouriteShort'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.UserFavourite'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Create user favourites
      tags:
      - favourites
  /favourites/:favouriteid:
    delete:
      description: Deletes a favourite for a specified user
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Delete user favourite
      tags:
      - favourites
    patch:
      description: updates a favourite for a specified user
      parameters:
      - description: UserFavouriteShort to update
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.UserFavouriteShort'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Update user favourites
      tags:
      - favourites
  /favourites/:userid:
    get:
      description: gets list of favourites for a specified user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserFavourite'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get user favourites
      tags:
      - favourites
swagger: "2.0"
