definitions:
  model.Audience:
    properties:
      ageFrom:
        type: integer
      ageTo:
        type: integer
      birthCountry:
        type: string
      gender:
        type: integer
      hoursSpentFrom:
        type: integer
      hoursSpentTo:
        type: integer
      id:
        type: string
      purchasesFrom:
        type: integer
      purchasesTo:
        type: integer
    type: object
  model.Chart:
    properties:
      dataPoints:
        items:
          $ref: '#/definitions/model.DataPoint'
        type: array
      id:
        type: string
      title:
        type: string
      xaxisTitle:
        type: string
      yaxisTitle:
        type: string
    type: object
  model.DataPoint:
    properties:
      x:
        type: number
      "y":
        type: number
    type: object
  model.Insight:
    properties:
      description:
        type: string
      id:
        type: string
    type: object
  model.UserFavourite:
    properties:
      audience:
        $ref: '#/definitions/model.Audience'
      chart:
        $ref: '#/definitions/model.Chart'
      description:
        type: string
      insight:
        $ref: '#/definitions/model.Insight'
    type: object
info:
  contact: {}
  title: Favourites API
paths:
  /favourites/:userid:
    get:
      description: gets list of favourites for a specified user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.UserFavourite'
            type: array
        "400":
          description: Bad Request
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get user favourites
      tags:
      - favourites
swagger: "2.0"
